name: Notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  fork:
    branches: [ main ]
  branch_protection_rule:
    types: [created, deleted]
jobs:

  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
    - name: send custom message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.USERID }}
        token: ${{ secrets.MULUGETA}}
        message: |
            # PushedBy: ${{ github.actor }}
            type:${{github.type}}
            Commit message: ${{ github.event.commits[0].message }}
            Project Url: portifolio
            Repository: ${{ github.repository }}


